[build]
  command = "npm install --prefix client && npm run build --prefix client"
  publish = "client/build"
  functions = "netlify/functions"

[dev]
  framework = "create-react-app"
  targetPort = 3000
  command = "npm start --prefix client"

[build.environment]
  NODE_VERSION = "20"